/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#f5faff',
        'primary-container': '#00eefc',
        'on-tertiary-fixed': '#1f0052',
        'surface-tint': '#8ff5ff',
        'surface-bright': '#1e2e38',
        'on-secondary-container': '#b1d6e4',
        'on-tertiary-fixed-variant': '#4700a7',
        'on-tertiary': '#290067',
        'primary-fixed-dim': '#00deec',
        'outline': '#6c777f',
        'background': '#050f16',
        'outline-variant': '#3f4951',
        'on-secondary': '#315561',
        'tertiary-dim': '#874cff',
        'on-surface-variant': '#a1adb5',
        'surface': '#050f16',
        'on-primary-fixed': '#003f43',
        'error-dim': '#d7383b',
        'inverse-on-surface': '#4c565e',
        'on-secondary-fixed-variant': '#3b5f6b',
        'error': '#ff716c',
        'tertiary': '#ac89ff',
        'primary': '#8ff5ff',
        'surface-container-low': '#09151c',
        'on-surface': '#dce7f0',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'tertiary-container': '#7000ff',
        'inverse-primary': '#006a71',
        'tertiary-fixed': '#bda1ff',
        'on-primary-container': '#005359',
        'on-primary': '#005d63',
        'on-primary-fixed-variant': '#005e64',
        'surface-container-highest': '#182831',
        'primary-dim': '#00deec',
        'surface-dim': '#050f16',
        'secondary-fixed-dim': '#b2d7e6',
        'on-error-container': '#ffa8a3',
        'primary-fixed': '#00eefc',
        'secondary-dim': '#b2d7e6',
        'surface-container-lowest': '#000000',
        'secondary-fixed': '#c0e6f4',
        'tertiary-fixed-dim': '#b190ff',
        'secondary': '#c0e6f4',
        'on-tertiary-container': '#f8f1ff',
        'on-secondary-fixed': '#1d424e',
        'surface-variant': '#182831',
        'surface-container-high': '#13212a',
        'secondary-container': '#274c57',
        'on-background': '#dce7f0',
        'surface-container': '#0e1b23',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        mono: ['Space Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      animation: {
        'spin-slow': 'spin 8s linear infinite',
        'reverse-spin': 'spin 8s linear infinite reverse',
        'marquee': 'marquee 30s linear infinite',
      },
      keyframes: {
        scan: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
}
